### ISSUE TITLE
i dont know how to work it

### ISSUE THREAD

**Issue by helpmeplc** [TFCNN/Projects#1]
how do i install it and use it and get it to learn

**Comment by eddskt** [comment]
> 

I would like the same information, I had an idea, I found the project through the article on [MEDIUM](https://medium.com/swlh/creating-a-machine-learning-auto-shoot-bot-for-cs-go-part-3-63dcc2d4b0e1) and I would really like to contribute, but there are not many details about the installation or implementation...
